version: '3.7'
services:
  db:
    image: postgres:15-alpine
    env_file:
      - data.ini
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  nats:
    container_name: "nats"
    image: nats:2.9.11-alpine
    restart: "unless-stopped"
    volumes:
      - "./nats:/etc/nats"
      - "./nats/jetstream:/data"
  bot:
    build: .
    command: sh -c "make migrate && python -m bot"
    env_file:
      - data.ini
    restart: always
    depends_on:
      - db
      - nats

volumes:
  pgdata: